name: PR title (Conventional Commits)

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
          requireScope: false
          subjectPattern: '^[^\s].+'
          ignoreLabels: 'skip-cc'
